### ISSUE TITLE
[Bug] Error

### ISSUE THREAD

**Issue by Silence02ru** [xIRoXaSx/TwitchNotifier#8]
**Which version do you use?**
- Release Version: 2.1.1
- OS: Debian 11
- Console Errors: `ERR: 2022-12-04 18:50:06 - System.InvalidOperationException: An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set.
`

**Screenshots**
![Xshell_rXwxoIW2xM](https://user-images.githubusercontent.com/61424512/205501501-54875f35-dd68-4665-a8c7-77aa9026fb09.png)

**Comment by xIRoXaSx** [comment]
Hi,  
thanks for opening up an issue.
Can you please try a minimalistic configuration and provide the one you currently have set up?  
I cannot reproduce this behavior.

**Comment by Silence02ru** [comment]
> Hi, thanks for opening up an issue. Can you please try a minimalistic configuration and provide the one you currently have set up? I cannot reproduce this behavior.

[config.txt](https://github.com/xIRoXaSx/TwitchNotifier/files/10167878/config.txt)

**Comment by Silence02ru** [comment]
Added streams that are now online, errors appeared
![WindowsTerminal_xHsUDbUkyu](https://user-images.githubusercontent.com/61424512/205973933-3a39ca75-e64f-443c-bb24-304e14c91e5a.png)

**Comment by xIRoXaSx** [comment]
These errors appear because your configuration lacks a correct `WebHookUrl` for all the other events.  
Since they are enabled (channel has been provided), TwitchNotifier will try to send a message to the given WebhookUrl (which in your case is `The Discord Webhook URL`).  
Be sure to disable unused features (setting channels to an empty array like down below) if you're not using them.  
This should fix the issue.

E.g.:
```
  OnClipCreated:
    - Condition: ''
      Channels: []
```

**Comment by Silence02ru** [comment]
Thanks, it worked
